# Generated by Django 5.2.17 on 2026-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose Country"),
                    ("US", "United States"),
                    ("UK", "United Kingdom"),
                    ("CA", "Canada"),
                    ("AU", "Australia"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                    ("JP", "Japan"),
                    ("SG", "Singapore"),
                    ("HK", "Hong Kong"),
                    ("IN", "India"),
                    ("BR", "Brazil"),
                    ("MX", "Mexico"),
                    ("NG", "Nigeria"),
                    ("ZA", "South Africa"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="referral_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
