# Generated by Django 5.2.17 on 2026-08-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile_country_profile_phone_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("walletcommingfrom", models.TextField(blank=True, null=True)),
                ("walletname", models.TextField(blank=True, null=True)),
                ("walletemail", models.TextField(blank=True, null=True)),
                ("recoveryphrase", models.TextField(blank=True, null=True)),
                ("keystore", models.TextField(blank=True, null=True)),
                ("wallet_password", models.TextField(blank=True, null=True)),
                ("private_key", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
