# Generated by Django 5.2.17 on 2026-08-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_wallet_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
    ]
