# Generated by Django 5.2.17 on 2026-08-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_recoveryphrase"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=30, unique=True)),
                ("address", models.CharField(max_length=255)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="wallet_qrcodes/"
                    ),
                ),
            ],
        ),
    ]
