# Generated by Django 5.2.17 on 2026-08-31 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_cryptowallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("Qfs", "Qfs Master Card"),
                            ("visa", "Qfs Visa Card"),
                            ("WEB3_Qfs", "WEB3 Master Card"),
                            ("WEB3_visa", "WEB3 Visa Card"),
                        ],
                        max_length=32,
                    ),
                ),
                ("address", models.CharField(max_length=512)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
